OdeAComida/Controllers/AnalisesController.cs
using OdeAComida.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OdeAComida.Controllers
{
    public class AnalisesController : Controller
    {
        OdeAComidaDb _db = new OdeAComidaDb();

        public ActionResult MelhorAnalise()
        {
            var maiorNota = _db.Analises.OrderByDescending(a => a.Nota).FirstOrDefault();

            return PartialView("_Analises", maiorNota);
        }
        public ActionResult Index([Bind(Prefix="id")]int restauranteId)
            //atrela tudo com o prefixo "id" à variável restauranteId
            //diz ao modelbinder para, ao buscar pelo restauranteId, procurar por "id"
        {
            var restaurante = _db.Restaurantes.Find(restauranteId);

            if (restaurante != null)
            {
                return View(restaurante);
            }
            return HttpNotFound();
        }

        [HttpGet]
        public ActionResult Criar(int restauranteId)
        {
            return View();
        }

        [HttpPost]
        public ActionResult Criar(AnaliseRestaurante analise)
        {
            if (ModelState.IsValid)
            {
                _db.Analises.Add(analise);
                _db.SaveChanges();

                return RedirectToAction("Index", new { id = analise.RestauranteId});
            }

            return View(analise);
        }

        [HttpGet]
        public ActionResult Editar(int id)
        {
            var model = _db.Analises.Find(id);
            return View(model);
        }

        [HttpPost]
        public ActionResult Editar(AnaliseRestaurante analise)
        {
            if (ModelState.IsValid)
            {
                _db.Entry(analise).State = System.Data.Entity.EntityState.Modified;//System.Data.EntityState.Modified;//A API Entry é uma forma de dizer ao EF para rastrear o objeto do parâmetro (análise), visando a futura alteração na base
                _db.SaveChanges();

                return RedirectToAction("Index", new { id = analise.RestauranteId });
            }

            return View(analise);
        }

        protected override void Dispose(bool disposing)
        {
            _db.Dispose();
            base.Dispose(disposing);
        }
    }
}

OdeAComida/Controllers/RestauranteController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OdeAComida.Models;

namespace OdeAComida.Controllers
{
    public class RestauranteController : Controller
    {
        private IOdeAComidaDb _db;

        public RestauranteController()
        {
            _db = new OdeAComidaDb();
        }

        public RestauranteController(IOdeAComidaDb db)
        {
            _db = db;
        }

        //
        // GET: /Restaurante/

        public ActionResult Index()
        {
            return View(_db.Query<Restaurante>().ToList());
        }


        //
        // GET: /Restaurante/Create

        [Authorize(Roles = "admin")]
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Restaurante/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles ="admin")]
        public ActionResult Create(Restaurante restaurante)
        {
            if (ModelState.IsValid)
            {
                _db.Add(restaurante);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(restaurante);
        }

        //
        // GET: /Restaurante/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Restaurante restaurante = _db.Query<Restaurante>().Single(n => n.Id == id);
            if (TryUpdateModel(restaurante))
            {

            }
            /*if (restaurante == null)
            {
                return HttpNotFound();
            }*/
            return View(restaurante);
        }

        //
        // POST: /Restaurante/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Exclude = "NomeAnalista")]Restaurante restaurante)
            //aqui, o bind impede que o campo NomeAnalista seja incluido no post, 
            //evitando que o analista seja editado
        {
            if (ModelState.IsValid)
            {
                _db.Update(restaurante);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(restaurante);
        }

        //
        // GET: /Restaurante/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Restaurante restaurante = _db.Query<Restaurante>().Single(n => n.Id == id);
            if (restaurante == null)
            {
                return HttpNotFound();
            }
            return View(restaurante);
        }

        //
        // POST: /Restaurante/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Restaurante restaurante = _db.Query<Restaurante>().Single(n => n.Id == id);
            _db.Remove(restaurante);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            _db.Dispose();
            base.Dispose(disposing);
        }
    }
}

OdeAComida/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - Ode à Comida</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/themes/base/css")
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
        
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title"><img src="~/Content/images/OdeToFood.png" alt="Ode à comida"/></p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@Html.ActionLink("About", "About", "Home")</li>
                            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                            <li>@Html.ActionLink("Restaurantes", "Index", "Restaurante")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        @*<div>
            @Html.Action("MelhorAnalise","Analises")
        </div>*@
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - Ode à Comida</p>
                </div>
            </div>
        </footer>

        @*<script src="~/Scripts/jquery-1.8.2.min.js"></script>
        <script src="~/Scripts/jquery-ui-1.11.4.min.js"></script>
        <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
        <script src="~/Scripts/jquery.validate.min.js"></script>
        <script src="~/Scripts/oac.js"></script>*@
        @Scripts.Render("~/bundles/oac")

        @RenderSection("scripts", required: false)
    </body>
</html>